---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: all
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    #- verify
    - destroy
platforms:
  - name: apps-windows-exporter-debian10
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian10
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: apps-windows-exporter-debian11
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian11
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: apps-windows-exporter-debiantiti
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debiantiti
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3.9"

verifier:
  name: ansible
